version: "3"

services:
  mysqldb:
    container_name: mysqldb
    image: mysql:8
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=tpachat
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    volumes:
      - /var/lib/mysql

  spring_app:
    image: khaledkhm/tpachatproject
    container_name: achatback
    restart: on-failure
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/tpachat?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    ports:
      - 8089:8089
    depends_on:
      - mysqldb
