version: "3"

services:
     mysqldb:
    container_name: mysqldb
    image: mysql/mysql-server:8.0
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=tpachat
      - MYSQL_USER=root
      - MYSQL_PASSWORD=1234
    volumes:
      - /var/lib/mysql

    springboot-be:
        depends_on:
          - mysqldb
        image: khaledkhm/tpachatproject:latest
        container_name: achatback
        env_file: ./.env
        environment:
          SPRING_APPLICATION_JSON: '{
            "spring.datasource.url"  : "jdbc:mysql://mysql-db:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?useSSL=false",
            "spring.datasource.username" : "$MYSQLDB_USER",
            "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
            "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
            "spring.jpa.hibernate.ddl-auto" : "update"
          }'
        ports:
          - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
        restart: on-failure
