version: '2'
services:
 nexus:
  image: sonatype/nexus3
  ports:
  - "8081:8081"
  volumes:
  - 'nexus-data:/nexus-data'
 prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    restart: unless-stopped
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
 grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    restart: unless-stopped
volumes:
  nexus-data:
  SonarQube_data:
  SonarQube_extensions:
  SonarQube_logs:
 