version: "3"

mysqldb:
    image: mysql:latest
    volumes:
      -  /home/mysql/khaledkhmdata:/var/lib/mysql:rw
    networks:
      - net-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=tpachat

springboot-be:
    depends_on:
      - mysql-db
    image: khaledkhm/tpachatproject:latest
    container_name: springboot-be
    env_file: ./.env
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysql-db:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?useSSL=false",
        "spring.datasource.username" : "$MYSQLDB_USER",
        "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    restart: on-failure

volumes:
  db:
