version : '3'
services:
  mysqldatabase:
    image: mysql:latest
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - 3306:3306



  tpachatproject:
    depends_on:
    - mysqldatabase
    image: khaledkhm/tpachatproject
    ports:
    - "8089:8089"
    restart: always
    container_name: achatback
    environment:
    - SPRING_DATASOURCE_URL= spring.datasource.url=jdbc:mysql://mysqldb:3306/tpachat?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
 
